### PR TITLE
implement chat resizing

### PR DESCRIPTION
**Pull request by KenanY**
Mostly just using bigscreen's implementation. Width is saved to local storage. Let me know of any issues.

Closes https://github.com/ILiedAboutCake/OverRustle/issues/42

### CODE REVIEW

**Comment by hayksaakian** [comment]
run 

`npm run prestart`

to make sure it compiles the jsx successfully

also note: this pull introduces some jquery code into the frontend, i'd rather move towards getting the whole site in react.js

@KenanY are you willing to re-write this into react when we get there?

**Comment by KenanY** [comment]
Yup compiles fine (no jsx introduced anyways) and tested locally. I agree that react would be better; I went this route because at the moment this part of the site is not in react.

**Comment by KenanY** [comment]
I see the resize bar itself is live but not the additions to `overrustle.js`. I didn't realize that the generated `js/` files were tracked by git as well so I did not include `js/overrustle.js` in this patch (imo it makes diffs twice as large); should I send a PR for that as well?

**Comment by hayksaakian** [comment]
cake can you run npm start from server and push to github master

**Comment by hayksaakian** [comment]
i don't remember why we do that @KenanY i'll add an issue to set up a bundler for frontend. 

i think it's because certain pages are react and other are not.

i suppose those other pages could just load bundle.js anyways.

i think we should switch to webpack

**Comment by KenanY** [comment]
@hayksaakian I think the services page would be easy to port to react, since it is simply a static page with a few `iframe`s. I might make the effort myself when I find the time. However, I have only every done single page stuff with react; for multi-page stuff like this, do you know if we need to would we need to use a client-side router module (assuming a single js for all pages)?

**Pull request merged**
